services:
  rstudio:
    container_name: r440seuratbp
    image: r440seuratbp:latest
    container_name: r440container
    image: r440image:latest
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=password
      - DISABLE_AUTH=true
      - RENV_PATHS_CACHE=/home/rstudio/.local/share/renv/cache
      - GITHUB_PAT=${GITHUB_PAT}
    volumes:
      - ./projects:/home/rstudio/projects
      - ./.devcontainer:/home/rstudio/.devcontainer
      - ${RENV_PATHS_CACHE_HOST}:/home/rstudio/.local/share/renv/cache
    env_file:
      - .env
    volumes:
      - ./projects:/home/rstudio/projects
      - ./.devcontainer:/home/rstudio/.devcontainer
      - ${RENV_PATHS_CACHE_HOST}:/home/rstudio/.local/share/renv/cache
